// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
  }
}

//# sourceMappingURL=web-routerRoutes.d.ts.map
