// This file was generated by RedwoodJS
import FatalErrorPageType from '/home/punisher/michamp/dev/michampwebsite/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/home/punisher/michamp/dev/michampwebsite/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/home/punisher/michamp/dev/michampwebsite/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
}

//# sourceMappingURL=web-routesPages.d.ts.map
